source 'https://github.com/CocoaPods/Specs.git'

# This line is needed until OGVKit is fully published to CocoaPods
# Remove once packages published:
# source 'https://github.com/brion/OGVKit-Specs.git'

use_frameworks!

def sharedPods
    pod 'AlamofireObjectMapper'
    pod 'AlamofireImage'
    pod 'JFCore', :path => '/Users/mobilepatagonia/Job/southfox/jfcore'
end

def iosPods
end

target 'LDLARadio' do
    iosPods
    sharedPods
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
