source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def sharedPods
    pod 'SwiftLint'
    pod 'AlamofireCoreData'
    pod 'JFCore', :git => 'https://github.com/patagonia2019/jfcore', :branch => 'master'
    #pod 'JFCore', :path => '/Users/fox/patagonia2019/jfcore'
    pod 'Firebase/Analytics'
    pod 'AlamofireImage'
end

def iosPods
  pod 'SwiftSpinner'
end

target 'LDLARadio' do
    platform :ios, '12.0'
    iosPods
    sharedPods
end


target 'LDLARadioTests' do
    platform :ios, '12.0'
    sharedPods
end

#target 'LDLARadio Extension' do
#  platform :watchos, '5.2'
#  sharedPods
#end
#
#
#target 'LDLARadioTVOS' do
#  platform :tvos, '12.0'
#  sharedPods
#end
#
#
#target 'LDLARadioMacOS' do
#  platform :macos, '10.14'
#  sharedPods
#end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
