source 'https://github.com/CocoaPods/Specs.git'

# This line is needed until OGVKit is fully published to CocoaPods
# Remove once packages published:
# source 'https://github.com/brion/OGVKit-Specs.git'

use_frameworks!

def sharedPods
    pod 'AlamofireObjectMapper'
    pod 'AlamofireImage'
    pod 'Localize-Swift', '~> 1.7'
    pod 'JFCore', :path => '/Users/javierfuchs/Job/southfox/jfcore'
end

def iosPods
    pod 'DGElasticPullToRefresh', '~> 1.1'
    pod 'NVActivityIndicatorView', '~> 3.1'
    pod 'SCLAlertView', '~> 0.7'
    pod 'SwiftIconFont', '~> 2.6'
    #    pod 'OGVKit'
end

target 'LDLARadio' do
    iosPods
    sharedPods
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
